/**
 * RU/EN gym search aliases → catalog tokens (English names, equipment, muscles).
 * Keys match via startsWith both ways + RU stems in filters.
 * Tokens are single words (query is split on spaces) — no multi-word keys.
 */
export const SEARCH_SYNONYMS: Record<string, string[]> = {
	// —— Base lifts ——
	жим: ['press', 'bench', 'chest', 'push', 'overhead'],
	жать: ['press', 'bench'],
	давить: ['press', 'bench'],
	лежа: ['bench', 'press', 'lie', 'lying'],
	лежачи: ['bench', 'press'],
	присед: ['squat', 'squats'],
	приседания: ['squat', 'squats'],
	приседы: ['squat', 'squats'],
	тяга: ['deadlift', 'row', 'pull', 'rdl', 'pulldown'],
	становая: ['deadlift'],
	становуха: ['deadlift'],
	румынская: ['romanian', 'rdl', 'deadlift'],
	румын: ['romanian', 'rdl', 'deadlift'],
	сумо: ['sumo', 'deadlift', 'squat'],
	rdl: ['romanian', 'deadlift'],

	// —— Bench / press variants ——
	наклонн: ['incline'],
	наклон: ['incline'],
	отрицательн: ['decline'],
	армейский: ['overhead', 'military', 'shoulder', 'press'],
	армейск: ['overhead', 'military', 'press'],
	военн: ['military', 'overhead', 'press'],
	стоя: ['overhead', 'standing', 'press'],
	сидя: ['seated'],
	французский: ['skull', 'crusher', 'extension', 'triceps'],
	француз: ['skull', 'extension', 'triceps'],
	скилл: ['skull', 'crusher'],

	// —— Equipment ——
	гантел: ['dumbbell', 'dumbbells'],
	гантели: ['dumbbell', 'dumbbells'],
	гантельки: ['dumbbell', 'dumbbells'],
	банки: ['dumbbell', 'dumbbells', 'biceps'],
	штанга: ['barbell'],
	штан: ['barbell'],
	блины: ['plate', 'barbell'],
	гиря: ['kettlebell'],
	гир: ['kettlebell'],
	молот: ['hammer'],
	молотки: ['hammer'],
	молоты: ['hammer'],
	молотков: ['hammer'],
	резинка: ['band', 'resistance'],
	резин: ['band'],
	эспандер: ['band', 'resistance'],
	блок: ['cable'],
	кроссовер: ['cable', 'crossover'],
	трос: ['cable'],
	смит: ['smith'],
	ez: ['ez barbell', 'ez'],
	изи: ['ez barbell', 'ez'],
	кривой: ['ez barbell', 'ez'],
	трэп: ['trap bar', 'trap'],
	трап: ['trap bar', 'trap'],
	медбол: ['medicine ball'],
	медболл: ['medicine ball'],
	фитбол: ['stability ball', 'ball'],
	босу: ['bosu'],
	роллер: ['roller', 'foam'],
	сани: ['sled'],
	покрышка: ['tire'],
	собственный: ['body weight'],
	тренажер: ['machine', 'leverage'],
	тренажёр: ['machine', 'leverage'],
	рычажн: ['leverage', 'machine'],

	// —— Pull / back ——
	подтягивания: ['pull up', 'pullup', 'chin', 'lats'],
	подтяг: ['pull up', 'pullup', 'lats'],
	турник: ['pull up', 'pullup', 'chin', 'lats'],
	чин: ['chin', 'pull up'],
	горизонтальная: ['row', 'seated'],
	гребля: ['row'],
	наклоне: ['bent', 'row'],
	пуловер: ['pullover'],
	шраги: ['shrug', 'traps'],
	шраг: ['shrug', 'traps'],
	гиперэкстензия: ['hyperextension', 'back extension', 'spine'],
	гипер: ['hyperextension', 'back extension'],
	экстензия: ['extension', 'hyperextension'],
	фейспал: ['face pull'],
	фейспол: ['face pull'],
	facepull: ['face pull'],

	// —— Push / chest / shoulders ——
	отжимания: ['push up', 'pushup', 'push-up', 'chest', 'dip'],
	отжим: ['push up', 'pushup', 'chest', 'dip'],
	брусья: ['dip', 'dips'],
	разведен: ['fly', 'flye', 'pec'],
	разводка: ['fly', 'flye'],
	разводки: ['fly', 'flye'],
	бабочка: ['fly', 'pec', 'pec deck'],
	сведен: ['fly', 'pec', 'cable'],
	сведения: ['fly', 'adduction'],
	махи: ['raise', 'fly', 'lateral'],
	боковые: ['lateral', 'raise'],
	передние: ['front', 'raise'],
	задние: ['rear', 'delt', 'face'],
	арнольд: ['arnold'],
	гудморнинг: ['good morning'],
	доброе: ['good'],
	утро: ['morning'],

	// —— Legs / glutes ——
	выпад: ['lunge', 'split'],
	выпады: ['lunge', 'split'],
	/** Popular RU name for Bulgarian split squat — not plain lunges. */
	болгарск: ['bulgarian', 'split'],
	болгарские: ['bulgarian', 'split'],
	болгарский: ['bulgarian', 'split'],
	сплит: ['split', 'bulgarian'],
	ягодиц: ['glutes', 'hip'],
	попа: ['glutes', 'hip'],
	ягодицы: ['glutes', 'hip'],
	хиптраст: ['hip thrust'],
	хип: ['hip', 'thrust', 'glutes'],
	тазов: ['hip', 'thrust', 'glutes'],
	мостик: ['bridge', 'glutes', 'hip'],
	квадрицепс: ['quads', 'squat'],
	квадры: ['quads'],
	икры: ['calves'],
	икронож: ['calves'],
	голени: ['calves', 'lower legs'],
	приводящ: ['adductors', 'adduction'],
	отводящ: ['abductors', 'abduction'],

	// —— Arms ——
	бицепс: ['biceps', 'curl'],
	бицух: ['biceps', 'curl'],
	бицуха: ['biceps', 'curl'],
	трицепс: ['triceps', 'extension'],
	трицух: ['triceps', 'extension'],
	сгибание: ['curl', 'biceps'],
	разгибание: ['extension', 'triceps'],
	концентрированн: ['concentration', 'curl'],
	предплеч: ['forearms', 'wrist'],
	кисти: ['forearms', 'wrist', 'grip'],

	// —— Core / cardio ——
	пресс: ['abs', 'waist', 'crunch', 'core'],
	скручивания: ['crunch', 'abs'],
	скручиван: ['crunch', 'abs'],
	планка: ['plank', 'core'],
	кор: ['core', 'abs', 'waist'],
	косые: ['obliques', 'abs'],
	вакуум: ['vacuum', 'abs', 'core'],
	берпи: ['burpee'],
	бёрпи: ['burpee'],
	кардио: ['cardio', 'run', 'bike'],
	бег: ['run', 'cardio', 'treadmill'],
	беговая: ['run', 'cardio'],
	велосипед: ['bike', 'cardio'],
	велотренажер: ['bike', 'cardio'],
	эллипс: ['elliptical', 'cardio'],
	эллипсоид: ['elliptical', 'cardio'],
	степпер: ['stepmill', 'cardio'],
	скакалка: ['jump rope', 'cardio', 'rope'],
	канаты: ['rope', 'battle'],

	// —— Olympic / functional ——
	рывок: ['snatch'],
	толчок: ['clean', 'jerk'],
	взятие: ['clean'],
	трастер: ['thruster'],
	трастеры: ['thruster'],
	фермеры: ['farmer'],
	фермерская: ['farmer'],
	прогулка: ['farmer', 'walk', 'carry'],

	// —— Body regions ——
	спина: ['back', 'lats', 'row', 'pulldown'],
	ноги: ['legs', 'quads', 'squat', 'lunge'],
	ногам: ['leg press', 'legs', 'squat'],
	ногами: ['leg press', 'legs'],
	плечи: ['shoulders', 'delts', 'press', 'raise'],
	дельты: ['delts', 'shoulders'],
	дельт: ['delts', 'shoulders'],
	трапеции: ['traps', 'shrug'],
	трапец: ['traps', 'shrug'],
	грудь: ['chest', 'pectorals', 'bench'],
	грудные: ['chest', 'pectorals'],
	руки: ['arms', 'biceps', 'triceps'],
	поясница: ['lower back', 'spine', 'hyperextension'],
	шея: ['neck'],
	задняя: ['hamstrings', 'rear']
};
